BaSP-TG: Delete, Add, Assign - Project
BaSP-m2022/samuel-trackgenix-server pull request #12
Opened 2022-05-11 01:41 UTC by DeepFreq

2022-05-11 23:28 UTC, SuarezAlexisEzequiel commented on src/index.js
>  const admins = require('./data/admins.json');
Si ya no se usa este require estaría bueno sacarlo y a su comentario correspondiente

2022-05-12 15:24 UTC, SuarezAlexisEzequiel approved these changes

2022-05-12 15:55 UTC, samueltrilloRR requested changes

2022-05-12 15:55 UTC, samueltrilloRR commented on package.json
> +    "nodemon": "^2.0.16"
Sacar nodemon de "dev dependencies"

2022-05-12 15:55 UTC, samueltrilloRR commented on package.json
> -    "nodemon": "^2.0.15"
Dejar "nodemon" como dependencia

2022-05-12 15:55 UTC, samueltrilloRR commented on src/resources/projects.js
> +
Eliminar espacio en blanco

2022-05-12 15:55 UTC, samueltrilloRR commented on src/resources/projects.js
> +
Eliminar espacio en blanco

2022-05-12 16:58 UTC, DeepFreq commented on package.json
> +    "nodemon": "^2.0.16"
Listo, echo.

2022-05-12 17:00 UTC, DeepFreq commented on src/resources/projects.js
> +
Listo, echo

2022-05-12 17:00 UTC, DeepFreq commented on src/resources/projects.js
> +
Echo

2022-05-12 17:55 UTC, samueltrilloRR requested changes

2022-05-12 17:55 UTC, samueltrilloRR commented on src/index.js
> +app.post('/:projectId/addMember', projectsControllers.assignRP);
Acomodar estas rutas por debajo de las rutas creadas por Iara para mantener la consistencia

2022-05-12 17:55 UTC, samueltrilloRR commented on package.json
> -    "nodemon": "^2.0.15"
Dejar la version 2.0.15 de nodemon

2022-05-12 18:08 UTC, samueltrilloRR approved these changes

2022-05-12 18:08 UTC, merged