TG-06: Created the schema for employee
BaSP-m2022/samuel-trackgenix-server pull request #18
Opened 2022-05-13 17:52 UTC by SuarezAlexisEzequiel

2022-05-13 20:41 UTC, marcomigliaro approved these changes

2022-05-13 21:04 UTC, samueltrilloRR requested changes

2022-05-13 21:04 UTC, samueltrilloRR commented on src/models/Employees.js
> +const mongoose = require('mongoose');
Usar import (ES6)

2022-05-13 21:04 UTC, samueltrilloRR commented on src/models/Employees.js
> +module.exports = Employees;
Usar export (ES6)

2022-05-14 00:02 UTC, samueltrilloRR approved these changes

2022-05-14 00:02 UTC, merged