TG-09: Schema for tasks created
BaSP-m2022/samuel-trackgenix-server pull request #19
Opened 2022-05-13 19:06 UTC by AlejandroSantini

2022-05-13 20:42 UTC, marcomigliaro approved these changes

2022-05-13 21:08 UTC, samueltrilloRR requested changes

2022-05-13 21:08 UTC, samueltrilloRR commented on src/models/Tasks.js
> +const mongoose = require('mongoose');
Usar import (ES6)

2022-05-13 21:08 UTC, samueltrilloRR commented on src/models/Tasks.js
> +});
Añadir un espacio despues de esta linea

2022-05-13 21:08 UTC, samueltrilloRR commented on src/models/Tasks.js
> +module.exports = Tasks;
Usar export (ES6)

2022-05-13 21:08 UTC, samueltrilloRR commented on src/models/Tasks.js
> +    type: Date,
Deberia de ser tipo numero

2022-05-14 04:42 UTC, samueltrilloRR approved these changes

2022-05-14 04:42 UTC, merged