TG-14: Add get by id and delete methods for time sheet resource
BaSP-m2022/samuel-trackgenix-server pull request #28
Opened 2022-05-17 14:57 UTC by marcomigliaro

2022-05-17 15:17 UTC, SuarezAlexisEzequiel commented on src/controllers/time-sheets.js
> +        return res.status(404).json({
Cuidado con el estado de error 404 porque tengo entendido que no devuelve el message

2022-05-17 15:21 UTC, SuarezAlexisEzequiel commented on src/controllers/time-sheets.js
> +      return res.status(404).json({
Misma situación en relacion al '404'.

2022-05-17 15:22 UTC, SuarezAlexisEzequiel approved these changes

2022-05-17 19:00 UTC, DeepFreq approved these changes

2022-05-17 21:25 UTC, Johsua30 approved these changes

2022-05-19 14:59 UTC, samueltrilloRR requested changes

2022-05-19 15:09 UTC, samueltrilloRR approved these changes

2022-05-19 15:09 UTC, merged