Tg 15 employee get get id delete
BaSP-m2022/samuel-trackgenix-server pull request #30
Opened 2022-05-17 18:56 UTC by Shirley1702

2022-05-17 19:10 UTC, DeepFreq requested changes

2022-05-17 19:10 UTC, DeepFreq commented on src/controllers/admins.js
> -};
Basado en los comentarios de Samu en otros PR, no hay que eliminar los archivos no asignados en la carpeta controllers. Por ende, revertir este archivo.

2022-05-17 19:10 UTC, DeepFreq commented on src/controllers/projects.js
> -};
No eliminar archivo.

2022-05-17 19:10 UTC, DeepFreq commented on src/controllers/super-admins.js
> -};
No eliminar archivo.

2022-05-17 19:10 UTC, DeepFreq commented on src/controllers/tasks.js
> -};
No eliminar archivo.

2022-05-17 19:10 UTC, DeepFreq commented on src/controllers/time-sheets.js
> -};
No eliminar archivo.

2022-05-17 19:10 UTC, DeepFreq commented on src/controllers/employees.js
> +                    msg: 'no hay nada',
Cambiar este mensaje a idioma ingles y con la primera letra en Mayúscula.

2022-05-17 19:10 UTC, DeepFreq commented on src/controllers/employees.js
> +            msg: 'this id no se borro',
Cambiar este mensaje a idioma ingles y con la primera letra en Mayúscula.

2022-05-17 20:01 UTC, Shirley1702 commented on src/controllers/employees.js
> +                    msg: 'no hay nada',
si!!! me olvide de cambiarlos.. porq me los hice de referencia

2022-05-18 02:04 UTC, SuarezAlexisEzequiel approved these changes
Me llama la atención el que hayas borrado el código tanto del package-lock, como de las controladoras, fuera de eso el código esta bien

2022-05-18 05:45 UTC, DeepFreq approved these changes

2022-05-19 18:31 UTC, nicolaslalicata commented on src/controllers/employees.js
> +            employeeAll = await EmployeeSchema.find(req.query)
a employeaAll agregar .length === 0 **(employeAll.length === 0)**

2022-05-19 19:50 UTC, samueltrilloRR requested changes

2022-05-19 19:50 UTC, samueltrilloRR commented on src/routes/index.js
> +    .use('/projects', projectsRoutes);
Las tres rutas estan repetidas. Habria que eliminarlas

2022-05-19 20:10 UTC, samueltrilloRR approved these changes

2022-05-19 20:10 UTC, merged