Tg-19: Task - Create, edit, getId, getAll, delete, validations
BaSP-m2022/samuel-trackgenix-server pull request #32
Opened 2022-05-17 23:37 UTC by AlejandroSantini

2022-05-18 02:31 UTC, SuarezAlexisEzequiel commented on src/index.js
> +// import * as tasksController from './controllers/tasks';
Estaría bueno que de no ser necesarios los comentarios se eliminen

2022-05-18 02:34 UTC, SuarezAlexisEzequiel approved these changes

2022-05-19 14:50 UTC, AlejandroSantini commented on src/index.js
> +// import * as tasksController from './controllers/tasks';
Gracias!

2022-05-19 14:50 UTC, AlejandroSantini commented on src/validations/tasks.js
> +const validateEdit = (req, res, next) => {
Gracias!

2022-05-19 15:23 UTC, samueltrilloRR requested changes

2022-05-19 15:31 UTC, AlejandroSantini commented on src/controllers/tasks.js
> +      msg: 'The request was successful',
joya

2022-05-19 15:49 UTC, samueltrilloRR approved these changes

2022-05-19 15:49 UTC, merged