BaSP-TG: Created the assigned task to get members by id, get all members and post new user.
BaSP-m2022/samuel-trackgenix-server pull request #8
Opened 2022-05-10 19:16 UTC by nicolaslalicata

2022-05-10 20:50 UTC, SuarezAlexisEzequiel approved these changes

2022-05-10 23:19 UTC, Johsua30 approved these changes

2022-05-10 23:53 UTC, cristulian approved these changes

2022-05-11 21:34 UTC, samueltrilloRR requested changes

2022-05-11 21:34 UTC, samueltrilloRR commented on package.json
> +    "file-system": "^2.2.2",
Eliminar esta dependencia. No era necesario instalar file-system. A su vez, eliminar tambien el archivo "package-lock.json"

2022-05-11 21:34 UTC, samueltrilloRR commented on src/index.js
> +
Añadir un comentario especificando el nombre del recurso, por ejemplo
` // Employees routes `

Y mover las rutas por debajo de las demas rutas explicitadas

2022-05-11 21:34 UTC, samueltrilloRR commented on src/resources/employees.js
> +  return res.status(200).json({ msg: 'User created successfully', newMember });
La respuesta tiene que respetar una estructura. Re escribirla de la siguiente manera
`  return res.status(200).json({ msg: 'User created successfully', data: newMember }); `

De la misma manera, en cada parte donde se haga esto.

2022-05-11 22:29 UTC, samueltrilloRR approved these changes

2022-05-11 22:29 UTC, merged