BaSP-TG:Time Sheets: GET-PUT-filterProject
BaSP-m2022/samuel-trackgenix-server pull request #9
Opened 2022-05-10 19:39 UTC by Shirley1702

2022-05-10 22:06 UTC, SuarezAlexisEzequiel commented on src/index.js
> +    res.status(200).json({
Estaría bueno chequear los espacios en blanco, y retirar los get y require peseteados de master del index (Los de admin)

2022-05-12 18:12 UTC, samueltrilloRR requested changes

2022-05-12 18:12 UTC, samueltrilloRR commented on src/resources/time-sheets.js
> +
Eliminar todas estas lineas (comentarios y espacios en blanco)

2022-05-12 18:53 UTC, samueltrilloRR approved these changes

2022-05-12 18:53 UTC, merged